In [0]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
# MNIST dataset provided by google in its colab
# understand the dataset by-
# #https://data-flair.training/blogs/tensorflow-mnist-dataset/

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [0]:
x = tf.placeholder(tf.float32, [None, 784])

In [0]:
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))
#using variable which is a modifiable tensor

In [0]:
y = tf.nn.softmax(tf.matmul(x, W) + b)
#softmax normalizes the weight
#https://data-flair.training/blogs/tensorflow-mnist-dataset/

In [0]:
y_ = tf.placeholder(tf.float32, [None, 10])

In [0]:
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))
#this formula is from maths see the site to understand
#https://cs.stackexchange.com/questions/60153/in-tensorflow-tutorials-why-do-they-use-only-the-first-term-of-cross-entropy-as
#y_ and tf.log(y) each similar index is being multiplied starting from i=0 to i=10
# reduce_sum is adding the columns of each row as reduction_indices=[1]
# https://stackoverflow.com/questions/47157692/how-does-reduce-sum-work-in-tensorflow
# reduce_mean is taking the mean by adding the values along both row and column since no indices is specified for it.
# but since after reduce_sum no column is there so it will add only row
#https://stackoverflow.com/questions/34236252/what-is-the-difference-between-np-mean-and-tf-reduce-mean

In [0]:
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)
#GradientDescentOptimizer(0.5) is a algorithm which we are using for training with learning rate 0.5

In [0]:
sess = tf.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [0]:
tf.global_variables_initializer().run()
#initialising the defined variables

In [0]:
for _ in range(1000):
  batch_xs, batch_ys = mnist.train.next_batch(100)
  sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})
# taking 1000 or less training data at each iteration

In [0]:
print(batch_ys)
# just to show the label data I have printed it
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
# argmax is finding the index with higher values and is returning it
# equal is comparing the two index and returing true or false
# https://stackoverflow.com/questions/41708572/tensorflow-questions-regarding-tf-argmax-and-tf-equal

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0.

In [0]:
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
#tf.cast is used to type cast the boolean value into float

In [0]:
print(sess.run(accuracy,feed_dict={x: mnist.test.images, y_: mnist.test.labels}))
# giving the test data as input

0.9183
